### ISSUE TITLE
I am a beginner in modeling. This is my first model that I have tried to reproduce. I have encountered two problems that may be very basic. I wonder if the author can provide some guidance?

### ISSUE THREAD

**Issue by CocoloNUt** [Bex0n/CelebA-VAE#1]
My environment configuration is as follows：
![图片](https://github.com/user-attachments/assets/ea20a27a-3cba-41c2-8b3b-dfa266ea1148)
python=3.9
now i meet this two questions:
1.
![图片](https://github.com/user-attachments/assets/88c0eda4-0fea-4b51-9290-b04b5f14795c)
2.
![图片](https://github.com/user-attachments/assets/96c2671f-0fdc-4e67-a7e4-e6fc3f6127ec)
My question may not be very detailed, but I want to know whether the reason why these two errors are triggered is due to version problems or my operating environment settings.
Thank everyone for any help they may provide

**Comment by Bex0n** [comment]
Recreated the environment with Python 3.9.18 and run successfully.

Can you please share the full stacktrace of the resulting error?

**Comment by Bex0n** [comment]
Please make sure the dataset is downloaded correctly, documented this step in README.md

**Comment by CocoloNUt** [comment]
Can you please share the full stacktrace of the resulting error?

Originally posted by @Bex0n in https://github.com/Bex0n/CelebA-VAE/issues/1#issuecomment-2564328835

Here is the full information, Maybe there is something wrong with the running environment I set up, but the data set should have been downloaded correctly. I dare not easily change your running code, I want to try to run it first and then analyze it

D:\Anaconda\envs\CeleVae\python.exe "C:\Users\whistler-kao'pan\Desktop\CelebA-VAE-main\CelebA-VAE-main\train.py"
True
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set torch.set_float32_matmul_precision('medium' | 'high') which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Files already downloaded and verified
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
| Name | Type | Params | Mode
0 | encoder | Encoder | 2.7 M | train
1 | decoder | Decoder | 1.8 M | train

4.5 M Trainable params
0 Non-trainable params
4.5 M Total params
17.947 Total estimated model params size (MB)
52 Modules in train mode
0 Modules in eval mode
D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:420: Consider setting persistent_workers=True in 'train_dataloader' to speed up the dataloader worker initialization.
True
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set torch.set_float32_matmul_precision('medium' | 'high') which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Files already downloaded and verified
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
| Name | Type | Params | Mode
0 | encoder | Encoder | 2.7 M | train
1 | decoder | Decoder | 1.8 M | train

4.5 M Trainable params
0 Non-trainable params
4.5 M Total params
17.947 Total estimated model params size (MB)
52 Modules in train mode
0 Modules in eval mode
D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:420: Consider setting persistent_workers=True in 'train_dataloader' to speed up the dataloader worker initialization.
Traceback (most recent call last):
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\call.py", line 47, in _call_and_handle_interrupt
return trainer_fn(*args, **kwargs)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 575, in _fit_impl
self._run(model, ckpt_path=ckpt_path)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 982, in _run
results = self._run_stage()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1026, in _run_stage
self.fit_loop.run()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 208, in run
self.setup_data()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 275, in setup_data
iter(self._data_fetcher) # creates the iterator inside the fetcher
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 105, in iter
super().iter()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 52, in iter
self.iterator = iter(self.combined_loader)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 351, in iter
iter(iterator)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 92, in iter
super().iter()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 43, in iter
self.iterators = [iter(iterable) for iterable in self.iterables]
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 43, in
self.iterators = [iter(iterable) for iterable in self.iterables]
File "D:\Anaconda\envs\CeleVae\lib\site-packages\torch\utils\data\dataloader.py", line 484, in iter
return self._get_iterator()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\torch\utils\data\dataloader.py", line 415, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\torch\utils\data\dataloader.py", line 1138, in init
w.start()
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\process.py", line 121, in start
self._popen = self._Popen(self)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\context.py", line 224, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\context.py", line 327, in _Popen
return Popen(process_obj)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\popen_spawn_win32.py", line 45, in init
prep_data = spawn.get_preparation_data(process_obj._name)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
_check_not_importing_main()
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
raise RuntimeError('''
RuntimeError:
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.

    This probably means that you are not using fork to start your
    child processes and you have forgotten to use the proper idiom
    in the main module:

        if __name__ == '__main__':
            freeze_support()
            ...

    The "freeze_support()" line can be omitted if the program
    is not going to be frozen to produce an executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 116, in spawn_main
exitcode = _main(fd, parent_sentinel)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 125, in _main
prepare(preparation_data)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 236, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
main_content = runpy.run_path(main_path,
File "D:\Anaconda\envs\CeleVae\lib\runpy.py", line 288, in run_path
return _run_module_code(code, init_globals, run_name,
File "D:\Anaconda\envs\CeleVae\lib\runpy.py", line 97, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "D:\Anaconda\envs\CeleVae\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\whistler-kao'pan\Desktop\CelebA-VAE-main\CelebA-VAE-main\train.py", line 68, in
trainer.fit(model=vanilla_vae, datamodule=data)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 539, in fit
call._call_and_handle_interrupt(
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\call.py", line 68, in _call_and_handle_interrupt
trainer._teardown()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1009, in _teardown
loop.teardown()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 502, in teardown
self._data_fetcher.teardown()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 80, in teardown
self.reset()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 142, in reset
super().reset()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 76, in reset
self.length = sized_len(self.combined_loader)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\lightning_fabric\utilities\data.py", line 52, in sized_len
length = len(dataloader) # type: ignore [arg-type]
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 358, in len
raise RuntimeError("Please call iter(combined_loader) first.")
RuntimeError: Please call iter(combined_loader) first.

**Comment by CocoloNUt** [comment]
`D:\Anaconda\envs\CeleVae\python.exe "C:\Users\whistler-kao'pan\Desktop\CelebA-VAE-main\CelebA-VAE-main\train.py"
True
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set torch.set_float32_matmul_precision('medium' | 'high') which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Files already downloaded and verified
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
| Name | Type | Params | Mode
0 | encoder | Encoder | 2.7 M | train
1 | decoder | Decoder | 1.8 M | train

4.5 M Trainable params
0 Non-trainable params
4.5 M Total params
17.947 Total estimated model params size (MB)
52 Modules in train mode
0 Modules in eval mode
D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:420: Consider setting persistent_workers=True in 'train_dataloader' to speed up the dataloader worker initialization.
True
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set torch.set_float32_matmul_precision('medium' | 'high') which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Files already downloaded and verified
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
| Name | Type | Params | Mode
0 | encoder | Encoder | 2.7 M | train
1 | decoder | Decoder | 1.8 M | train

4.5 M Trainable params
0 Non-trainable params
4.5 M Total params
17.947 Total estimated model params size (MB)
52 Modules in train mode
0 Modules in eval mode
D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:420: Consider setting persistent_workers=True in 'train_dataloader' to speed up the dataloader worker initialization.
Traceback (most recent call last):
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\call.py", line 47, in _call_and_handle_interrupt
return trainer_fn(*args, **kwargs)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 575, in _fit_impl
self._run(model, ckpt_path=ckpt_path)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 982, in _run
results = self._run_stage()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1026, in _run_stage
self.fit_loop.run()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 208, in run
self.setup_data()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 275, in setup_data
iter(self._data_fetcher) # creates the iterator inside the fetcher
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 105, in iter
super().iter()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 52, in iter
self.iterator = iter(self.combined_loader)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 351, in iter
iter(iterator)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 92, in iter
super().iter()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 43, in iter
self.iterators = [iter(iterable) for iterable in self.iterables]
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 43, in
self.iterators = [iter(iterable) for iterable in self.iterables]
File "D:\Anaconda\envs\CeleVae\lib\site-packages\torch\utils\data\dataloader.py", line 484, in iter
return self._get_iterator()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\torch\utils\data\dataloader.py", line 415, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\torch\utils\data\dataloader.py", line 1138, in init
w.start()
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\process.py", line 121, in start
self._popen = self._Popen(self)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\context.py", line 224, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\context.py", line 327, in _Popen
return Popen(process_obj)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\popen_spawn_win32.py", line 45, in init
prep_data = spawn.get_preparation_data(process_obj._name)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
_check_not_importing_main()
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
raise RuntimeError('''
RuntimeError:
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.

    This probably means that you are not using fork to start your
    child processes and you have forgotten to use the proper idiom
    in the main module:

        if __name__ == '__main__':
            freeze_support()
            ...

    The "freeze_support()" line can be omitted if the program
    is not going to be frozen to produce an executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 116, in spawn_main
exitcode = _main(fd, parent_sentinel)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 125, in _main
prepare(preparation_data)
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 236, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "D:\Anaconda\envs\CeleVae\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
main_content = runpy.run_path(main_path,
File "D:\Anaconda\envs\CeleVae\lib\runpy.py", line 288, in run_path
return _run_module_code(code, init_globals, run_name,
File "D:\Anaconda\envs\CeleVae\lib\runpy.py", line 97, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "D:\Anaconda\envs\CeleVae\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\whistler-kao'pan\Desktop\CelebA-VAE-main\CelebA-VAE-main\train.py", line 68, in
trainer.fit(model=vanilla_vae, datamodule=data)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 539, in fit
call._call_and_handle_interrupt(
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\call.py", line 68, in _call_and_handle_interrupt
trainer._teardown()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1009, in _teardown
loop.teardown()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 502, in teardown
self._data_fetcher.teardown()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 80, in teardown
self.reset()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 142, in reset
super().reset()
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\loops\fetchers.py", line 76, in reset
self.length = sized_len(self.combined_loader)
File "D:\Anaconda\envs\CeleVae\lib\site-packages\lightning_fabric\utilities\data.py", line 52, in sized_len
length = len(dataloader) # type: ignore [arg-type]
File "D:\Anaconda\envs\CeleVae\lib\site-packages\pytorch_lightning\utilities\combined_loader.py", line 358, in len
raise RuntimeError("Please call iter(combined_loader) first.")
RuntimeError: Please call iter(combined_loader) first.`
